version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: onruf
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/onruf
      PORT: 4000
      JWT_SECRET: change-this-secret
      CORS_ORIGIN: http://localhost:3000
    depends_on:
      - db
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  db_data:
